# Generated by Django 4.0.6 on 2022-07-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.TextField(blank=True, default=None, null=True)),
                ('art_abstract', models.TextField(blank=True, default=None, null=True)),
                ('art_affiliations', models.TextField(blank=True, default=None, null=True)),
                ('art_authors', models.TextField(blank=True, default=None, null=True)),
                ('art_journal', models.TextField(blank=True, default=None, null=True)),
                ('art_keyword', models.TextField(blank=True, default=None, null=True)),
                ('art_url', models.TextField()),
                ('art_publish_year', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('art_date_created', models.DateTimeField(editable=False)),
                ('art_date_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_login', models.EmailField(max_length=250)),
                ('use_password', models.CharField(max_length=128)),
                ('use_is_valid', models.BooleanField(default=False)),
                ('use_status', models.BooleanField(default=False)),
                ('use_date_created', models.DateTimeField(editable=False)),
                ('use_date_updated', models.DateTimeField()),
                ('use_date_deleted', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wei_score', models.DecimalField(decimal_places=3, default=10, max_digits=5)),
                ('wei_probability', models.DecimalField(decimal_places=6, max_digits=9)),
                ('wei_date_created', models.DateTimeField(editable=False)),
                ('wei_date_updated', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.article')),
            ],
        ),
    ]
