# Generated by Django 4.0.6 on 2022-07-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE OR REPLACE VIEW db_articlesweight '
            '   AS SELECT '
            '       pu.id AS article_id, '
            '       pu.art_score/ps.total_score AS wei_probability '
            '    FROM db_article pu '
            '    JOIN( '
            '        SELECT id, SUM(art_score) as total_score '
            '        FROM db_article '
            '    ) AS ps '
            '    GROUP BY pu.id '
            '    ORDER BY pu.id ASC;'
        )
    ]
